#!/bin/bash

# set -o xtrace

ns="backup2"

function size_full {
    local snapshot="$1"
    zfs send --parsable --raw -nv "$snapshot" | awk '/^size/ {print $2}'
}

function size_inc {
    local snapshot_start="$1"
    local snapshot_end="$2"
    zfs send --parsable --raw -nv -i "$snapshot_start" "$snapshot_end" | awk '/^size/ {print $2}'
}

function newname {
    date --utc "+$ns-%Y-%m-%dT%H-%M-%S"
}

function init {
    set -o errexit
    set -o pipefail
    local dataset_from="$1"
    local dataset_to="$2"
    local name
    name=$(newname)
    local snapshot_from="${dataset_from}@${name}"
    local snapshot_to="${dataset_to}@${name}"
    if zfs list "$dataset_to" >/dev/null 2>&1; then
        echo "error: destination dataset already exist"
        exit 1
    fi
    zfs snapshot "$snapshot_from"
    zfs hold $ns "$snapshot_from"
    local transfer_size
    transfer_size=$(size_full "$snapshot_from")
    # --raw to send encrypted data w/o decrypt/encrypt roundtrip
    zfs send --raw "$snapshot_from" | pv --size "$transfer_size" | zfs receive "$snapshot_to"
    zfs set readonly=on "$dataset_to"
    zfs set atime=off "$dataset_to"
    zfs set "${ns}:snapshot_last=$name" "$dataset_to"
    exit 0
}

function incremental {
    set -o errexit
    set -o pipefail
    local dataset_from="$1"
    local dataset_to="$2"
    local name_last="$3"
    local name
    name=$(newname)
    local snapshot_last="${dataset_from}@${name_last}"
    local snapshot_from="${dataset_from}@${name}"
    local snapshot_to="${dataset_to}@${name}"
    # create new snapshot
    zfs snapshot "$snapshot_from"
    # hold this snapshot for deletion
    zfs hold $ns "$snapshot_from"
    local transfer_size
    transfer_size=$(size_inc "$snapshot_last" "$snapshot_from")
    zfs send --raw -i "$snapshot_last" "$snapshot_from" | pv --size "$transfer_size" | zfs receive "$snapshot_to"
    zfs set "${ns}:snapshot_last=$name" "$dataset_to"
    # release previous snapshot for deletion
    zfs release $ns "$snapshot_last"
    exit 0
}

function usage {
    echo "usage: $0 [--init] --from dataset/from --to dataset/to"
}

do_init=false
dataset_from=""
dataset_to=""
original_args=( "${@}" )

while [[ $# -gt 0 ]]; do
    case "$1" in
        --init)
            do_init=true
            shift
            ;;
        --from)
            shift
            dataset_from="$1"
            shift
            ;;
        --to)
            shift
            dataset_to="$1"
            shift
            ;;
        -h|--help)
            usage
            exit 1
            ;;
        *)
            echo "unknown arg: $1"
            usage
            exit 1
            ;;
    esac
done

if [[ $dataset_from = "" ]]; then
    echo "missing --from dataset"
    usage
    exit 1
fi
if [[ $dataset_to = "" ]]; then
    echo "missing --to dataset"
    usage
    exit 1
fi

if $do_init; then 
    echo "init: yes" 
else
    echo "init: no" 
fi
echo "from: $dataset_from"
echo "to:   $dataset_to"

if $do_init; then
    init "$dataset_from" "$dataset_to"
    exit 0
fi

if ! zfs list "$dataset_to" >/dev/null 2>&1; then
    echo "error: destination dataset doesn't exist, rerun with --init:"
    echo "$0 --init" "${original_args[@]}"
    exit 1
fi

snapshot_last=$(zfs get -H -o value "$ns:snapshot_last" "$dataset_to")
if [[ "$snapshot_last" == "-" ]]; then
    echo "destination dataset exists but no snapshot name from last backup found, use other to dataset?"
    exit 1
fi

incremental "$dataset_from" "$dataset_to" "$snapshot_last"
